### ISSUE TITLE
Error when trying to run the project

### ISSUE THREAD

**Issue by Joseph-Rance** [KashParty/backprop#1]
**System information**
windows 10
tensorflow-2.1.0
-Keras 2.3.1
Python 3.6 :
Minecraft 1.16.2

**Standalone code to reproduce the issue**
from kashparty import backprop
backprop.go()

**Logs**
```
Using a backend.
2020-08-20 22:15:05,618 [WARNI] From /Users/.../python/compat/v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-08-20 22:15:05,669 [DEBUG] ARGGGG VUE GET IT OUT
2020-08-20 22:15:05,673 [DEBUG] WHERE IS THE PYTHON
2020-08-20 22:15:05,799 [DEBUG] I WANT PYTHON
2020-08-20 22:15:05,802 [INFO ] Arguments:
2020-08-20 22:15:05,802 [INFO ] Namespace(distinct lack of python)
2020-08-20 22:15:05.803552: I kashparty/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-20 22:15:05.817263: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
2020-08-20 22:15:05,817 [INFO ] NGL python would have been easier
2020-08-20 22:15:05,817 [INFO ] NUMPY FTW
2020-08-20 22:15:05,817 [INFO ] TF >>>VUE, even for front end (trust me)
./dataset_management/redd/washingmachine/washingmachine_validation_.csv
2020-08-20 22:15:05,838 [WARNI] From /Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.init (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
File "/Users/Ziyue/Desktop/BitcnNILM-master/s2swA_train.py", line 189, in <- ive given up changing file locations from this random error i pasted from tensorflow/tensorflow
pretrainedmodel_dir=args.pretrainedmodel_dir)
File "/Users/Ziyue/Desktop/BitcnNILM-master/s2swA_Model.py", line 70, in get_model
lstm1 = Bidirectional(LSTM(512, return_sequences=True, stateful=True))(cnn2)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/layers/wrappers.py", line 437, in call
return super(Bidirectional, self).call(inputs, **kwargs)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
return func(*args, **kwargs)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in call
self.build(unpack_singleton(input_shapes))
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/layers/wrappers.py", line 581, in build
self.forward_layer.build(input_shape)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/layers/recurrent.py", line 502, in build
self.cell.build(step_input_shape)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1942, in build
constraint=self.bias_constraint)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 282, in add_weight
constraint=constraint)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 620, in variable
value, dtype=dtype, name=name, constraint=constraint)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 814, in variable
constraint=constraint)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 260, in call
return cls._variable_v2_call(*args, **kwargs)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
shape=shape)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 235, in
previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2645, in default_variable_creator_v2
shape=shape)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in call
return super(VariableMetaclass, cls).call(*args, **kwargs)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in init
distribute_strategy=distribute_strategy)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1543, in _init_from_args
name="initial_value", dtype=dtype)
File "/Users/Ziyue/opt/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1280, in convert_to_tensor
raise RuntimeError("Attempting to capture an EagerTensor without "
IsaacHoltError: Failed to run. Cannot stand to look at Vue.js anymore
```

**Comment by KashParty** [comment]
@Joseph-Rance Thanks, I'll look into it. For now, maybe you need to try with a more up-to-date version of Minecraft.
